# -*- coding: utf-8 -*-
"""Expt 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fIJW1eRgn0ORTXU1pSH1dPkXU56rI6B
"""

pip install pgmpy

from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
import networkx as nx
import pylab as plt

cpd_guest = TabularCPD('Guest',3,[[0.33],[0.33],[0.33]])
cpd_price = TabularCPD('Price',3,[[0.33],[0.33],[0.33]])
cpd_host = TabularCPD('Host',3,[[0,0,0,0,0.5,1,0,1,0.5],
                                [0.5,0,1,0,0,0,1,0,0.5],
                                [0.5,1,0,1,0.5,0,0,0,0]],
                      evidence=['Guest','Price'],evidence_card=[3,3])

from pgmpy.models import BayesianModel  # Import BayesianModel directly in this cell

model = BayesianModel([('Guest', 'Host'), ('Price', 'Host')])

model.add_cpds(cpd_guest, cpd_price, cpd_host)

model.check_model()

from pgmpy.inference import VariableElimination

infer = VariableElimination(model)
posterior_p = infer.query(['Host'],evidence ={'Guest':2,'Price':2})
print(posterior_p)

import networkx as nx
import matplotlib.pyplot as plt

model = nx.DiGraph()

model.add_nodes_from (['Guest','Price','Host'])

model.add_edges_from([('Guest','Host'),('Price','Host')])

nx.draw(model,with_labels=True)
plt.show()
plt.savefig('Final-output.png')
plt.close()